### ISSUE TITLE
Nested quotes with no spaces not handled

### ISSUE THREAD

**Issue by rafamel** [mccormicka/string-argv#15]
Hi, congrats on the lib! It is a dependency for the [`exits`](https://github.com/rafamel/exits) bin, and I've found this to be an issue on `string-argv`@0.1.2:

```javascript
const toArgv = require('string-argv');
console.log(toArgv('jake run:silent["echo 1"]'));
```

**Expect:** `[ 'jake', 'run:silent["echo 1"]' ]`
**Get:** `[ 'jake', 'run:silent["echo 1"', ']' ]`

**Comment by Cellule** [comment]
Thank you for reporting this. I found a fix for this and will release a patch soon

**Comment by rafamel** [comment]
Fantastic, @Cellule ! Thanks for the fix! Will be on the lookout for that patch release ;)

**Comment by Cellule** [comment]
I have released a new version.
I decided to bump the version to 0.2.0 because my fix was a significant change to the regex used and it changes the parsing behavior drastically for nested quotes. I doubt it would break anyone, but I didn't want to take the chance

**Comment by rafamel** [comment]
Great, I would have done the same ;)
