### ISSUE TITLE
v2.0.0 published a git repo

### ISSUE THREAD

**Issue by rafamel** [mccormicka/string-argv#17]
The last version published to npm included the git repo. This causes conflicts w/ npm when removing.

**Comment by Cellule** [comment]
Sorry about that, not sure why this wasn't a problem before. 
I've updated the .npmignore file 26d956a83e3bdb8ca526f712339521ddd2534e01 and published version 0.2.1 c5f80ac49b7a4a388cd07f2747f80dc443891a9e
