### ISSUE TITLE
Missing license file

### ISSUE THREAD

**Issue by char0n** [mccormicka/string-argv#9]
Hello, is is possible to incorporate the LICENSE file inside the repository and the npm package. Now it's missing. It's implied by MIT license that if licensed under the MIT the source code must be accompanied by full license text. If the license file is not in the npm package or the repo a lot of people cannot use it.

Thank you

**Comment by Cellule** [comment]
Thanks for bringing this to my attention.
The Commit 37a8648b19b88c0605aba086f2a9221eecac03db added the LICENSE file for MIT license

I have published version 0.1 which contains the LICENSE file
https://www.npmjs.com/package/string-argv

**Comment by char0n** [comment]
cool. Unfortunately you have to fill the year and copyright holder. Without it, the license is still invalid. 

https://github.com/mccormicka/string-argv/commit/37a8648b19b88c0605aba086f2a9221eecac03db#diff-9879d6db96fd29134fc802214163b95aR3

**Comment by Cellule** [comment]
Sorry, I don't know much about licensing, there is no copyright on this code, can I just remove that part from the license file ?

**Comment by char0n** [comment]
The copyright notice is the most important part of the license. If you read the license, it specifically deals with the copyright notice. It has to be some physical or legal entity. In this case I’d say it needs to be you because you are the author.

**Comment by Cellule** [comment]
I have published a new version with the fixed License file

**Comment by char0n** [comment]
@Cellule thanks. Now anybody can use your library and there should be no problem when library appears as transient dependency for other libraries.
